### PR TITLE
Fixed a potential typo

### PR DESCRIPTION
**Pull request by Vedant1202**
## Description
Fixing a potential typo by replacing 'purely intentional' with 'purely unintentional'.

### Additional Comments
I'm not so sure if this is a genuine typo error, or I am missing an _intentional_ piece of humor.

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Funny! 😆😄

**Comment by Vedant1202** [comment]
Glad to help!

**Comment by bl-ue** [comment]
ping @darrachequesne could we get this merged?

**Comment by darrachequesne** [comment]
Given that it's the second PR about this line, I think we'll just remove it :smile:  

Closed by https://github.com/socketio/socket.io-website/commit/f8d01844f8554ac92d9e1fcc6b1a2444719c411a.

**Comment by bl-ue** [comment]
Oh, was that not a typo?

**Comment by darrachequesne** [comment]
No it wasn't :angel:

**Comment by Vedant1202** [comment]
Oh okay, I had second thoughts about it being intentional

**Pull request closed without merging**
