### PR TITLE
Favicon is added

### PR DESCRIPTION
**Pull request by sercaneraslan**

### CODE REVIEW

**Comment by darrachequesne** [comment]
@sercaneraslan thanks for the pull request! A question though, shouldn't we provide a `favicon.ico` instead?

**Comment by sercaneraslan** [comment]
@darrachequesne You're welcome. You can look this article: "What is the purpose of favicon.png?"

https://css-tricks.com/favicon-quiz/#article-header-id-2

**Comment by darrachequesne** [comment]
Yep, "standards"... :smile:  Thanks!

**Comment by sercaneraslan** [comment]
You're welcome 👍

**Pull request merged**
